/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
static yyconst short int yy_accept[196] =
    {   0,
        0,    0,   89,   87,    2,    2,   74,   87,   40,   80,
       73,   68,   69,   78,   77,   65,   76,   72,   79,   38,
       66,   62,   81,   67,   82,   85,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   70,   71,   83,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       63,   84,   64,   75,   61,    0,   86,   39,   47,   64,
       56,   48,   45,   53,   43,   54,   44,   55,   37,    1,
       46,   40,    0,   38,   71,   63,   70,   52,   58,   60,
       59,   51,   40,   40,   40,   40,   40,   36,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   49,   40,

       40,   40,   40,   40,   40,   40,   28,   40,   40,   40,
       40,   40,   40,   40,   50,   57,   42,   41,   40,   40,
       40,   14,   40,   40,   16,   23,   17,   12,   18,   13,
       40,   15,   40,   40,   40,   40,   40,   40,   29,   40,
       40,   40,   40,   40,   40,   20,   40,    9,    8,   10,
       40,   40,   40,   40,   34,    6,   40,   40,   40,   40,
       27,    3,   40,   22,   40,   40,   40,   40,   35,   40,
       11,   40,   21,   31,   40,   40,    0,   40,    4,   40,
       40,   30,   24,   25,   40,   40,    0,   19,   33,    5,
       40,    7,   26,   32,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   29,   29,
       32,   29,   33,   29,   29,   34,   35,   36,   37,   38,
       29,   29,   39,   40,   29,   41,   42,   29,   29,   29,
       43,    1,   44,   45,   27,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   29,   29,   55,   56,   57,
       58,   59,   29,   60,   61,   62,   63,   64,   65,   29,
       29,   29,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[199] =
    {   0,
        0,    0,  355,  356,  356,  356,  330,  347,    0,   46,
       63,  356,  356,  328,   60,  356,   61,   59,   68,   75,
      326,  356,   75,  326,   50,  356,  333,   72,   66,   73,
       74,   65,   89,   81,   84,   85,   90,  356,  356,  324,
       92,   91,   98,   93,  104,   99,  107,  100,  108,  109,
      356,  103,  356,  356,  356,  341,  340,    0,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  110,  356,
      356,  329,  114,  124,  356,  356,  356,  320,  356,  356,
      356,  319,  121,  119,  147,  129,  120,  326,  123,  133,
      151,  153,  155,  156,  157,  158,  160,  161,  356,  162,

      163,  164,  165,  166,  168,  167,  325,  173,  175,  176,
      169,  179,  174,  181,  356,  356,  356,  356,  178,  183,
      184,  324,  185,  189,  323,  322,  321,  187,  320,  319,
      186,  318,  188,  191,  192,  194,  196,  195,  317,  206,
      209,  198,  222,  210,  223,  316,  227,  315,  310,  306,
      228,  231,  232,  233,  305,  304,  235,  236,  241,  242,
      255,  303,  246,  301,  245,  248,  249,  250,  300,  252,
      298,  247,  297,  288,  253,  254,  249,  256,  285,  258,
      259,  278,  277,  276,  260,  262,  240,  272,  271,  268,
      261,  267,  356,  265,  356,  324,  277,  326

    } ;

static yyconst short int yy_def[199] =
    {   0,
      195,    1,  195,  195,  195,  195,  195,  196,  197,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  198,
      195,  195,  195,  195,  195,  195,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  195,  195,  195,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      195,  195,  195,  195,  195,  196,  196,  197,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  198,  195,  198,  195,  195,  195,  195,  195,  195,
      195,  195,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  195,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  195,  195,  195,  195,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  195,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  195,  198,  198,  198,
      198,  198,  195,  198,    0,  195,  195,  195

    } ;

static yyconst short int yy_nxt[426] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   27,   29,
       30,   31,   32,   33,   27,   27,   27,   34,   35,   36,
       37,   27,   38,   39,   40,   27,   27,   41,   42,   43,
       44,   27,   27,   45,   27,   27,   27,   27,   46,   47,
       48,   27,   27,   49,   50,   51,   52,   53,   54,   59,
       60,   61,   64,   81,   82,   66,   69,   69,   69,   70,
      195,  195,   76,   65,   67,   68,   62,  195,  195,  195,
       73,   71,   74,   74,   74,   77,  195,   78,   79,  195,

      195,   83,   86,   90,  195,  195,  195,  195,  195,   88,
       84,   85,   97,  195,  195,  195,   95,   94,   92,  195,
       87,   91,  195,  195,  195,   93,  115,   69,   69,   69,
       89,   69,   69,   69,  195,  195,  195,  100,  195,   73,
      103,   74,   74,   74,  195,   96,  101,   98,  195,  102,
      105,  120,  104,  113,  107,  106,  111,  119,  110,  108,
      109,  114,  195,  125,  112,  123,  195,  122,  195,  116,
      195,  195,  195,  195,  121,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  124,  128,  127,  195,  195,
      195,  195,  130,  195,  195,  132,  195,  129,  195,  195,

      195,  195,  195,  195,  195,  153,  195,  195,  135,  195,
      195,  195,  126,  195,  133,  137,  148,  131,  149,  150,
      136,  195,  134,  140,  195,  195,  138,  139,  142,  143,
      144,  141,  145,  146,  147,  152,  155,  195,  195,  154,
      156,  160,  195,  195,  161,  151,  195,  195,  195,  171,
      195,  195,  157,  162,  158,  159,  195,  195,  177,  164,
      195,  195,  195,  195,  195,  195,  163,  195,  195,  195,
      195,  195,  166,  195,  195,  195,  195,  195,  165,   58,
      195,  168,  195,  195,  167,  170,  195,  195,  169,  172,
      193,  195,  195,  195,  175,  173,  181,  174,  184,  182,

      195,  183,  187,  195,  176,  178,  179,  180,  186,  185,
      194,  190,  195,  195,  189,  195,  195,  188,  195,  195,
      195,  195,  191,  192,   56,  195,   56,   56,   72,   72,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  118,  117,  195,   57,   57,   99,  195,   80,
       75,   63,   57,   55,  195,    3,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195
    } ;

static yyconst short int yy_chk[426] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   10,
       10,   11,   15,   25,   25,   17,   18,   18,   18,   19,
       32,   29,   23,   15,   17,   17,   11,   28,   30,   31,
       20,   19,   20,   20,   20,   23,   34,   23,   23,   35,

       36,   28,   29,   31,   33,   37,   42,   41,   44,   30,
       28,   28,   36,   43,   46,   48,   35,   34,   33,   45,
       29,   32,   47,   49,   50,   33,   52,   69,   69,   69,
       30,   73,   73,   73,   84,   87,   83,   41,   89,   74,
       42,   74,   74,   74,   86,   35,   41,   37,   90,   41,
       44,   84,   43,   49,   45,   44,   47,   83,   46,   45,
       45,   50,   85,   90,   48,   87,   91,   86,   92,   52,
       93,   94,   95,   96,   85,   97,   98,  100,  101,  102,
      103,  104,  106,  105,  111,   89,   93,   92,  108,  113,
      109,  110,   95,  119,  112,   97,  114,   94,  120,  121,

      123,  131,  128,  133,  124,  128,  134,  135,  101,  136,
      138,  137,   91,  142,   98,  103,  119,   96,  120,  121,
      102,  140,  100,  106,  141,  144,  104,  105,  109,  110,
      111,  108,  112,  113,  114,  124,  133,  143,  145,  131,
      134,  137,  147,  151,  138,  123,  152,  153,  154,  153,
      157,  158,  135,  140,  136,  136,  159,  160,  161,  142,
      165,  163,  172,  166,  167,  168,  141,  170,  175,  176,
      161,  178,  144,  180,  181,  185,  191,  186,  143,  197,
      194,  147,  192,  190,  145,  152,  189,  188,  151,  154,
      187,  184,  183,  182,  159,  157,  167,  158,  172,  168,

      179,  170,  177,  174,  160,  163,  165,  166,  176,  175,
      191,  181,  173,  171,  180,  169,  164,  178,  162,  156,
      155,  150,  185,  186,  196,  149,  196,  196,  198,  198,
      148,  146,  139,  132,  130,  129,  127,  126,  125,  122,
      107,   88,   82,   78,   72,   57,   56,   40,   27,   24,
       21,   14,    8,    7,    3,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "kazi.l"
#define INITIAL 0
/*
    
    Bismillahir Rahmanir Rahim. 
    Every praise goes to ALLAH for our wellbeing.
    Code : Kazi Fahim Tahmid
    Judge: Codeforces
    Date : 2023-10-17 19.02
 
    
*/
/*     -------------- C files include --------------        */
#line 15 "kazi.l"
    #include "kazi.tab.h"
    #include <string.h>
    int yyparse();
    int yylex();  
    int yyerror();
    FILE *flexo;
    void count();
    int multicomm=0;
/*     -------------- Keyword Section for Patters --------------        */
/*     -------------- Pattern Matching Rules Section --------------        */
#line 546 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 40 "kazi.l"

#line 699 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 196 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 356 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "kazi.l"
{ 
    comment();
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "kazi.l"
{
    count();
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 1 : %s\n",yytext);
    return FUNC;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 2 : %s\n",yytext);
    return PRINT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 2.1 : %s\n",yytext);
    return SWITCH;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 2.2 : %s\n",yytext);
    return CASE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 2.2 : %s\n",yytext);
    return def_ault;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 3 : %s\n",yytext);
    return ASIN;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 4 : %s\n",yytext);
    return ACOS;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 5 : %s\n",yytext);
    return ATAN;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 6 : %s\n",yytext);
    return LOG10;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 7 : %s\n",yytext);
    return LOG;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 8 : %s\n",yytext);
    return SIN;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 102 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 9 : %s\n",yytext);
    return COS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 107 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 10 : %s\n",yytext);
    return TAN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 11 : %s\n",yytext);
    return GCD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 12 : %s\n",yytext);
    return LCM;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 13 : %s\n",yytext);
    return POW;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 127 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 14 : %s\n",yytext);
    return IMPORT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 132 "kazi.l"
{ 
    count();
    fprintf(flexo,"LEX 15 : %s\n",yytext);
    return VAR;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 137 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 16 : %s\n",yytext);
    return CLASS;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 142 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 17 : %s\n",yytext);
    return INIT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 18 : %s\n",yytext);
    return INT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 19 : %s\n",yytext);
    return DOUBLE;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 157 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 20 : %s\n",yytext);
    return STRING;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 21 : %s\n",yytext);
    return ELSEIF;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 167 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 22 : %s\n",yytext);
    return ELSE;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 172 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 23 : %s\n",yytext);
    return IF;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 177 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 24 : %s\n",yytext);
    return FOR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 25 : %s\n",yytext);
    return WHILE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 187 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 26 : %s\n",yytext);
    return CONST;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 192 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 27 : %s\n",yytext);
    return CONTINUE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 197 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 28 : %s\n",yytext);
    return RETURN;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 202 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 29 : %s\n",yytext);
    return VOID;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 207 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 30 : %s\n",yytext);
    return CLASS;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 212 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 81 : %s\n",yytext);
    return DO;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 217 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 31 : %s\n",yytext);
    yylval.val.doubleval = atof(yytext);
    yylval.val.type = 3;
    return NUM;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 224 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 32: %s\n",yytext);
    yylval.val.intval = atoi(yytext);
    yylval.val.type = 2;
    return NUM;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 231 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 33 : %s\n",yytext);
    strcpy(yylval.text,yytext+1);
   // printf("Came :: %s\n",yylval.text);
    return VARACCESS;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 238 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 34: %s\n",yytext);
    strcpy(yylval.text,yytext);
    return NAME;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 244 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 35 : %s\n",yytext);
    return(RIGHT_ASSIGN); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 247 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 36 : %s\n",yytext);
    return(LEFT_ASSIGN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 250 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 37 : %s\n",yytext);
    return(ADD_ASSIGN); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 253 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 38 : %s\n",yytext);
    return(SUB_ASSIGN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 256 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 39 : %s\n",yytext);
    return(MUL_ASSIGN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 259 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 40 : %s\n",yytext);
    return(DIV_ASSIGN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 262 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 41 : %s\n",yytext);
    return(MOD_ASSIGN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 265 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 42 : %s\n",yytext);
    return(AND_ASSIGN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 268 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 43 : %s\n",yytext);
    return(XOR_ASSIGN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 271 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 44 : %s\n",yytext);
    return(OR_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 274 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 45 : %s\n",yytext);
    return(RIGHT_OP); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 277 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 46 : %s\n",yytext);
    return(LEFT_OP); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 280 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 47 : %s\n",yytext);
    return(INC_OP); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 283 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 48 : %s\n",yytext);
    return(DEC_OP); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 286 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 49 : %s\n",yytext);
    return(PTR_OP); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 289 "kazi.l"
{ count();
    fprintf(flexo,"LEX 50 : %s\n",yytext);
     return(AND_OP); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 292 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 51 : %s\n",yytext);
    return(OR_OP); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 295 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 52 : %s\n",yytext);
    return(LE_OP); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 298 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 53 : %s\n",yytext);
    return(GE_OP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 301 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 54 : %s\n",yytext);
    return(EQ_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 304 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 55 : %s\n",yytext);
    return(NE_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 308 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 56 : %s\n",yytext);
    return(';'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 311 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 57 : %s\n",yytext);
    return('{'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 314 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 58 : %s\n",yytext);
    return('}'); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 317 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 59 : %s\n",yytext);
    return(','); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 320 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 60 : %s\n",yytext);
    return(':'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 323 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 61 : %s\n",yytext);
    return('='); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 326 "kazi.l"
{ count();
    fprintf(flexo,"LEX 62 : %s\n",yytext);
     return('('); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 329 "kazi.l"
{ count();
    fprintf(flexo,"LEX 63 : %s\n",yytext);
     return(')'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 332 "kazi.l"
{ count();
    fprintf(flexo,"LEX 64 : %s\n",yytext);
     return('['); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 335 "kazi.l"
{ count();
    fprintf(flexo,"LEX 65 : %s\n",yytext);
     return(']'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 338 "kazi.l"
{ count();
    fprintf(flexo,"LEX 66 : %s\n",yytext);
     return('.'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 341 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 67 : %s\n",yytext);
    return('&'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 344 "kazi.l"
{ count();
    fprintf(flexo,"LEX 68 : %s\n",yytext);
     return('!'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 347 "kazi.l"
{ count();
    fprintf(flexo,"LEX 69 : %s\n",yytext);
     return('~'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 350 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 70 : %s\n",yytext);
    return('-'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 353 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 71 : %s\n",yytext);
    return('+'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 356 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 72 : %s\n",yytext);
    return('*'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 359 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 73 : %s\n",yytext);
    return('/'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 362 "kazi.l"
{ count();
    fprintf(flexo,"LEX 74 : %s\n",yytext);
     return('%'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 365 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 75 : %s\n",yytext);
    return('<'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 368 "kazi.l"
{ count(); 
    fprintf(flexo,"LEX 76 : %s\n",yytext);
    return('>'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 371 "kazi.l"
{ count();
    fprintf(flexo,"LEX 77 : %s\n",yytext);
     return('^'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 374 "kazi.l"
{ count();
    fprintf(flexo,"LEX 78 : %s\n",yytext);
     return('|'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 377 "kazi.l"
{ count();
    fprintf(flexo,"LEX 79 : %s\n",yytext);
     return('?'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 381 "kazi.l"
{
    count();
    fprintf(flexo,"LEX 80 : %s\n",yytext);
    yylval.val.type = 4;
    yylval.val.strval = calloc(strlen(yytext),sizeof(char));
    strcpy(yylval.val.strval,yytext+1);
    yylval.val.strval[strlen(yylval.val.strval)-1]=0;
    return STR;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 390 "kazi.l"
{
    printf("Error :: Unknown character\n");
    exit(-1);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 394 "kazi.l"
ECHO;
	YY_BREAK
#line 1486 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 196 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 196 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 195);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 394 "kazi.l"

int yywrap () {
	return 1;
}
void comment() {
	char c, c1;
loop:
	while ((c = input()) != '*' && c != 0)
		putchar(c);

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0)
		putchar(c1);
}
int column = 0;
FILE *infotext;
void count () {
    int i;
    for(int i=0;yytext[i]!='\0';i++)
    {
        if(yytext[i]=='\n')
            column=0;
        else if(yytext[i]=='\t')
            column+=(8-(column%8));
        else column++;
    }
    ECHO;
}
int main () {
    freopen("input.txt","r",stdin);
	flexo = fopen("lex_out.txt","w");
    infotext = fopen("info.txt","w");
    yyparse();
    fclose(flexo);
}